# Build docker image from master and push it to GitHub packages
name: Docker
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '34 3 2 * *'
  workflow_dispatch:  # Allow manual trigger from GitHub UI
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: package docker
        run: |
          docker login docker.pkg.github.com --username Tallcraft --password ${{ secrets.GITHUB_TOKEN }}
          docker build . --file Dockerfile --tag docker.pkg.github.com/tallcraft/tc-api-server/app:master
          docker push docker.pkg.github.com/tallcraft/tc-api-server/app:master
        env:
          CI: true
